apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: demo-deployment 
spec: 
  selector: 
    matchLabels: 
      app: dotnet
  replicas: 1 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: dotnet 
    spec: 
      containers: 
      - name: dotnet 
        image: appimages
        ports: 
        - containerPort: 3000 
      imagePullSecrets:
        - name: secret-jfrog
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: dotnet-service 
spec: 
  selector: 
    app: dotnet 
  ports: 
  - protocol: TCP 
    port: 3000 
    targetPort: 3000 
  type: LoadBalancer